@API_HostAddress = http://localhost:5217

GET {{API_HostAddress}}/recommendations/genres/tv
Accept: application/json

###

GET {{API_HostAddress}}/recommendations/genres/movie
Accept: application/json

###