@API_HostAddress = http://localhost:5217

GET {{API_HostAddress}}/api/billboard/intelligent?startDate=2025-08-25&endDate=2026-09-25&bigRooms=2&smallRooms=2&filterByMostSuccessful=true
Accept: application/json

###

GET {{API_HostAddress}}/api/billboard/intelligent?startDate=2025-08-30&endDate=2025-09-30&bigRooms=2&smallRooms=2&filterByMostSuccessful=false
Accept: application/json

### 

GET https://api.themoviedb.org/3/discover/movie?api_key=4e3eb8df6994ad943cadecf85a0a97fe
